language: elixir

elixir:
  - '1.8.1'
otp_release:
  - '21.2.6'

install:
  mix local.rebar --force; mix local.hex --force; mix deps.get

stages:
  - test
  - name: create_git_tag
    if: branch = automatic-semver
  - name: docker_build
    if: tag =~ ^v
  # - deploy

jobs:
  include:
    - stage: test
      name: "Unit Tests"
      script: mix test --cover
    - stage: test
      name: "Credo"
      script: mix credo --strict
    - stage: create_git_tag
      script:
        git config --global credential.helper store &&
        echo $GIT_CI_CREDENTIALS > $HOME/.git-credentials &&
        git tag v0.0.0 &&
        git push origin v0.0.0
    - stage: docker_build
      script: echo "something here to test"
